while 1:
    try:
        raise Exception()
    except Exception:
        pass
